version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  server:
    build: .
    container_name: ollama-server
    ports:
      - "8321:8321"
    environment:
      - INFERENCE_MODEL=llama3.2:1b-instruct-fp16
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - .:/app  # Optional: live sync local changes (useful in dev)

volumes:
  ollama_data:
